### ISSUE TITLE
Question on DtoD/peer copy

### ISSUE THREAD

**Issue by leofang** [leofang/cupy#8]
Hi @maxpkatz I hope you don’t mind me bugging you again 😅 

Just one quick question (I hope) for clarifying the behavior: When using `cudaMemcpyAsync` or `cudaMemcpyPeerAsync` to copy between two devices, which device should the `stream` argument reside, source or destination? I found the documentation is unclear about this, and after some tests I suspect it’s source. Am I right? 

Thanks!

**Comment by leofang** [comment]
Another question: Does `cudaMemcpy*Async` silently create a stream internally if the passed-in stream is 0 or invalid?

**Comment by maxpkatz** [comment]
@leofang It's advised to have the `stream` argument reside on the source GPU, but the copy will still work if that is not the case. Indeed, in some cases your stream will be ignored for the perspective of actually doing the copy and the CUDA driver will use its own internal resources, but the stream semantics will still be honored (that is, things that are launched in the stream after the copy will not start until after the copy is done).

**Comment by leofang** [comment]
Thanks for confirming, Max! 

I did some experiments this afternoon. I tried scattering a big array on device 0 to smaller ones on device 0, 1, 2, 3, and then gathering back to device 0, and I noticed that the driver could make its own decision whether to overlap the peer copy or not?! 

What I mean is: Sometimes the throughput is large, but all transfers are kinda "serialized" (they're still on different streams, but from nvvp timeline they look like launched one by one). This mostly happens during scattering. Other times, the throughput is small, but 4 transfers are overlapped (each on a different stream). This happens during gathering. 

Interestingly, the total time for scattering and gathering is roughly the same. Is the driver really smart enough to do this, or did I do something wrong?

**Comment by leofang** [comment]
I tested this on a DGX-2 btw, which has nv links.

**Comment by maxpkatz** [comment]
> Is the driver really smart enough to do this

Yes, it is smart enough to do that. It is similar to (though not exactly the same as) how when there are multiple kernels running in different streams, the driver can either choose to run them concurrently or to serialize them. It attempts to make the best decision given the circumstances.
